on:
  pull_request:
    types: [opened]

jobs:
  test:
    # if: github.event.pull_request.user.login == 'dependabot-preview[bot]' || github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: A job to bump POM and ChangeLog
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Uses POM Version Bump
        uses: wlicamele-bw/pom-version-bump@v1.0
        id: bump
        with:
          bumpVersionType: bump
          bumpVersion: patch
          bumpChangelog: true
          changelogDesc: ${{ github.event.pull_request.title }}
      - name: Get the version number
        run: echo "The Version Number is ${{ steps.bump.outputs.versionNumber }}"