on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  test:
    # if: github.event.pull_request.user.login == 'dependabot-preview[bot]' || github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: A job to bump POM and ChangeLog
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Get Version
        id: pom-version
        run: echo "::set-output name=version::mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version"
      - name: Print Version
        run: echo "The version we just got is ${{ steps.pom-version.outputs.version }}"
      - name: Uses POM Version Bump
        uses: wlicamele-bw/pom-version-bump@v0.2
        id: bump
        with:
          bumpVersionType: bump
          bumpVersion: patch
          bumpChangelog: false
          #changelogDesc: ${{ github.event.pull_request.title }}
          mainBranchName: ${{ github.base_ref }}
      - name: Get the version number
        run: echo "The Version Number is ${{ steps.bump.outputs.versionNumber }}"