name: Build

on:
  push:
    branches:
      - feature/*

jobs:
  remove-old-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Extract Maven project version
        uses: 3nauk/bbcron-action-maven-getinfo@2077456a25ba01f73c9bfdf6638251bd5d7c9aed
        id: maven-info

      - run: echo "${{ steps.maven-info.outputs.version }}"

      - run: echo "${{ steps.maven-info.outputs.artifactId }}"

      - run: echo "${{ steps.maven-info.outputs.groupId }}"

      - name: ‼️Remove PackageVersion
        uses: 3nauk/bbcron-action-remove-packages@fc28300cbff1dcf4945d48b2eeb58f39ba0918c3
        with:
          organization: '3nauk'
          packageName: ${{ steps.maven-info.outputs.groupId }}.${{ steps.maven-info.outputs.artifactId }}
          #packageName: 'com.bnauk.bbcron.bbcron-core'
          packageVersion: ${{ steps.maven-info.outputs.version }}
          token: ${{secrets.bnauk_token}}
